export const siteConfig = {
  url: "https://arikko.dev",
  title: "Arik Chakma - Developer, creator.",
  description: "Developer, content creator, and an explorer.",
  keywords: [
    "Arik Chakma",
    "Arik",
    "Chakma",
    "Arik Chakma Blog",
    "Arik Chakma Website",
    "Arik Chakma Developer",
    "Arik Chakma Content Creator",
    "Arik Chakma Explorer",
    "Frontend Developer",
    "Frontend Engineer",
    "Software Engineer",
  ],
  author: "Arik Chakma",
  twitter: "@imarikchakma",
  social: [
    "https://x.com/imarikchakma",
    "https://github.com/arikchakma",
    "https://instagram.com/imarikchakma/",
  ],
};
