import { siteConfig } from "./config";

/**
 * URL of the build-time generated OpenGraph image for a writing.
 * Generated by `scripts/generate-og.tsx` into `public/images/og-images/`.
 */
export function getOpenGraphImage(id: string) {
  return `${siteConfig.url}/images/og-images/writings/${id}.png`;
}
