import Head from 'next/head';
import Image from 'next/image';
import Step from '../components/Step';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Step number="0" title="Generated by create next app" />
      </main>
    </div>
  );
}
